### PR TITLE
V1.0.4

### PR DESCRIPTION
**Pull request by Aisha-D**
- Include reference fasta as input
- Decide build from reference name
- Updated stratification files
- Linked to #11

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)* status: all files reviewed, 5 unresolved discussions (waiting on @Aisha-D)

___
*[Readme.md, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHc6rOC_Gkf-cmDgoL:-MdHc6rOC_Gkf-cmDgoM:b3tksed) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/17923f4497580f00051dbb339489885692033dba/Readme.md#L55)):*
> ```
> ## What are the limitations of this app
> ```
Which references can be used in the new version?
___
*[src/code.sh, line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHZjq37WrzgKdcRxm4:-MdHZjq47X7xSJlcFiaE:b-kdary8) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L15)):*
> ```
> ····
> ```
whitespace
___
*[src/code.sh, line 28 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHaKjAAcEpd0mOCTAk:-MdHaKjB9GaZ2sBoNgLI:b-irs9v6) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L28)):*
> ```
> touch
> ```
All indentation should be spaces not tabs
___
*[src/code.sh, line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdH_GqD3HxFyfMpHifD:-MdH_GqD3HxFyfMpHifE:bni0ath) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L81)):*
> ```
> build=$(echo $reference_fasta_path | rev | cut -d / -f 1| rev | cut -d "." -f1)
> ```
A slightly less convoluted method, which is easier to understand and maintain:
```
build=$(basename "$reference_fasta_path" | cut -d. -f1)
```
___
*[src/code.sh, line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHatxzD2_Nz4SVIa5E:-MdHaty--gRVzBlD3VbB:bhgd40x) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L89)):*
<details><summary><i alt="summary">Quoted 77 lines of code…</i></summary>

> ```
> 	# If build37 download build37 reference, else download build 38 references
> 	if [ "$build" = "hs37d5" ]; then
> 		echo "Using build37 reference genome."
> 		#Extract required resources from assets folder into /home/dnanexus/
> 		gunzip $reference_fasta_path
> 		reference_fasta_path=$(echo ${reference_fasta_path%.*})
> 		samtools faidx $reference_fasta_path
> 		# ~/hs37d5-fasta.tar -> ~/hs37d5.fa ~from 001 Reference > genomes > b37
> 		dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-Fjp4k3j4yBGpK4x73bzbG2P0 | tar xf -
> 		# ~/hs37d5-sdf.tar -> ~/hs37d5.sdf/ ~from 001 Reference > genomes > b37
> 		dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-G3670yj433GqkZKzB1vz9qZv | gunzip | tar xf - # v2 stratification
> 		# ~/GA4GH_GENOME_STRATIFICATION_V2.0_GRCH37.TAR.GZ -> ~/work/GRCh37/ ~from 001 Reference > giab > b37
> 		#The v2.0-GRCh37-stratifications.tsv file is a master file
> 		#containing relative filepaths to all of the bed files used by
> 		#hap.py for results stratifcation.
> 		#v2.0-GRCh37-stratifications.tsv must not be moved as its
> 		#relative path to the bed file will be changed if moved.
> 		#Run hap.py in docker container
> 		#The optional arguments used are the same as those used when running the precisionFDA GA4GH Benchmarking in vcfeval-partial-credit mode and other options left as default
> 		#Mount /home/dnanexus/ to /data/
> 		#For input files that are stored in /home/dnanexus/in/... replace '/home/dnanexus' with '/data' in filepath using: ${orig_filepath/home\/dnanexus/data}
> 		#If sample is flagged as NA12878, use v2.0 GRCh37 stratifications bed files (indexed in v2.0-GRCh37-stratifications.tsv) to provide additional stratification of results
> 		if $na12878; then
> 			echo "NA12878 sample so running hap.py with stratification"
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data} --stratification data//work/GRCh37/v2.0-GRCh37-stratifications.tsv \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		#Else if sample is not flagged as NA12878, run same command as above but without the stratification option
> 		else
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data} \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		fi
> 	elif [ "$build" = "GRCh38" ]; then
> 		echo "Using build38 reference genome."
> 
> 		#Extract required resources from assets folder into /home/dnanexus/
> 		gunzip $reference_fasta_path
> 		#Remove the .gz suffix from reference_fasta filepath
> 		reference_fasta_path=$(echo ${reference_fasta_path%.*})
> 		#Strip chr from reference file
> 		sed -i 's/chr//' $reference_fasta_path
> 		#Generate the fai file from stripped new fasta file
> 		samtools faidx $reference_fasta_path
> 		#No sdf is generated - this speeds up the process of hap.py but
> 		#not a necessary requirement.
> 		dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-G368PFQ433GVf490Bfk5ZZ26 | gunzip | tar xf -
> 		# ~/GA4GH_GENOME_STRATIFICATION_V2.0_GRCH38.TAR.GZ -> ~/work/GRch38/ ~from 001 Reference > giab > b38
> 		#The v2.0-GRCh38-stratifications.tsv file is a master file
> 		#containing relative filepaths to all of the bed files used by
> 		#hap.py for results stratifcation.
> 		#v2.0-GRCh38-stratifications.tsv must not be moved as its
> 		#relative path to the bed file will be changed if hs.
> 		#Run hap.py in docker container
> 		#The optional arguments used are the same as those used when running the precisionFDA GA4GH Benchmarking in vcfeval-partial-credit mode and other options left as default
> 		#Mount /home/dnanexus/ to /data/
> 		#For input files that are stored in /home/dnanexus/in/... replace '/home/dnanexus' with '/data' in filepath using: ${orig_filepath/home\/dnanexus/data}
> 		#If sample is flagged as NA12878, use v2.0 GRCh38 stratifications bed files (indexed in v2.0-GRCh38-stratifications.tsv) to provide additional stratification of results
> 		if $na12878; then
> 			echo "NA12878 sample so running hap.py with stratification"
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data} --stratification /data/work/genome_stratification_v2.0_GRCh38/v2.0-GRCh38-stratifications.tsv \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		#Else if sample is not flagged as NA12878, run same command as above but without the stratification option
> 		else
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data}  \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		fi
> ```
</details>

Not DRY - same code is repeated twice, but tweaked for different builds.
It would be better to collect build specific inputs as variables first, then enter the docker run block and use these variables

e.g.
```
if build == 37:
  a=1
  b=2
  c=3
elif build == 38:
  a=4
  b=5
  c=6

docker run -a $a -b $b -c $c
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[src/code.sh, line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHZjq37WrzgKdcRxm4:-MdqWlBe4IteHPrXua47:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ····
> ```
whitespace
</blockquote></details>

Done.
___
*[src/code.sh, line 28 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHaKjAAcEpd0mOCTAk:-MdqWkX-D0HbTnKRWTqV:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L28)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> touch
> ```
All indentation should be spaces not tabs
</blockquote></details>

Done.
___
*[src/code.sh, line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdH_GqD3HxFyfMpHifD:-MdqJ3x15VgOq2v1wm1I:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L81)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> build=$(echo $reference_fasta_path | rev | cut -d / -f 1| rev | cut -d "." -f1)
> ```
A slightly less convoluted method, which is easier to understand and maintain:
```
build=$(basename "$reference_fasta_path" | cut -d. -f1)
```
</blockquote></details>

Done.
___
*[src/code.sh, line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHatxzD2_Nz4SVIa5E:-MdvCrz_5FZU2PPcXest:bgvq0ac) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/af9d6e1ecb0b5466c4e7e1098d3e226fa5300e65/src/code.sh#L89)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 	# If build37 download build37 reference, else download build 38 references
> 	if [ "$build" = "hs37d5" ]; then
> 		echo "Using build37 reference genome."
> 		#Extract required resources from assets folder into /home/dnanexus/
> 		gunzip $reference_fasta_path
> 		reference_fasta_path=$(echo ${reference_fasta_path%.*})
> 		samtools faidx $reference_fasta_path
> 		# ~/hs37d5-fasta.tar -> ~/hs37d5.fa ~from 001 Reference > genomes > b37
> 		dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-Fjp4k3j4yBGpK4x73bzbG2P0 | tar xf -
> 		# ~/hs37d5-sdf.tar -> ~/hs37d5.sdf/ ~from 001 Reference > genomes > b37
> 		dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-G3670yj433GqkZKzB1vz9qZv | gunzip | tar xf - # v2 stratification
> 		# ~/GA4GH_GENOME_STRATIFICATION_V2.0_GRCH37.TAR.GZ -> ~/work/GRCh37/ ~from 001 Reference > giab > b37
> 		#The v2.0-GRCh37-stratifications.tsv file is a master file
> 		#containing relative filepaths to all of the bed files used by
> 		#hap.py for results stratifcation.
> 		#v2.0-GRCh37-stratifications.tsv must not be moved as its
> 		#relative path to the bed file will be changed if moved.
> 		#Run hap.py in docker container
> 		#The optional arguments used are the same as those used when running the precisionFDA GA4GH Benchmarking in vcfeval-partial-credit mode and other options left as default
> 		#Mount /home/dnanexus/ to /data/
> 		#For input files that are stored in /home/dnanexus/in/... replace '/home/dnanexus' with '/data' in filepath using: ${orig_filepath/home\/dnanexus/data}
> 		#If sample is flagged as NA12878, use v2.0 GRCh37 stratifications bed files (indexed in v2.0-GRCh37-stratifications.tsv) to provide additional stratification of results
> 		if $na12878; then
> 			echo "NA12878 sample so running hap.py with stratification"
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data} --stratification data//work/GRCh37/v2.0-GRCh37-stratifications.tsv \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		#Else if sample is not flagged as NA12878, run same command as above but without the stratification option
> 		else
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data} \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		fi
> 	elif [ "$build" = "GRCh38" ]; then
> 		echo "Using build38 reference genome."
> 
> 		#Extract required resources from assets folder into /home/dnanexus/
> 		gunzip $reference_fasta_path
> 		#Remove the .gz suffix from reference_fasta filepath
> 		reference_fasta_path=$(echo ${reference_fasta_path%.*})
> 		#Strip chr from reference file
> 		sed -i 's/chr//' $reference_fasta_path
> 		#Generate the fai file from stripped new fasta file
> 		samtools faidx $reference_fasta_path
> 		#No sdf is generated - this speeds up the process of hap.py but
> 		#not a necessary requirement.
> 		dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-G368PFQ433GVf490Bfk5ZZ26 | gunzip | tar xf -
> 		# ~/GA4GH_GENOME_STRATIFICATION_V2.0_GRCH38.TAR.GZ -> ~/work/GRch38/ ~from 001 Reference > giab > b38
> 		#The v2.0-GRCh38-stratifications.tsv file is a master file
> 		#containing relative filepaths to all of the bed files used by
> 		#hap.py for results stratifcation.
> 		#v2.0-GRCh38-stratifications.tsv must not be moved as its
> 		#relative path to the bed file will be changed if hs.
> 		#Run hap.py in docker container
> 		#The optional arguments used are the same as those used when running the precisionFDA GA4GH Benchmarking in vcfeval-partial-credit mode and other options left as default
> 		#Mount /home/dnanexus/ to /data/
> 		#For input files that are stored in /home/dnanexus/in/... replace '/home/dnanexus' with '/data' in filepath using: ${orig_filepath/home\/dnanexus/data}
> 		#If sample is flagged as NA12878, use v2.0 GRCh38 stratifications bed files (indexed in v2.0-GRCh38-stratifications.tsv) to provide additional stratification of results
> 		if $na12878; then
> 			echo "NA12878 sample so running hap.py with stratification"
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data} --stratification /data/work/genome_stratification_v2.0_GRCh38/v2.0-GRCh38-stratifications.tsv \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		#Else if sample is not flagged as NA12878, run same command as above but without the stratification option
> 		else
> 			dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
> 				-r ${reference_fasta_path/home\/dnanexus/data}  \
> 				--gender female --decompose --leftshift --adjust-conf-regions \
> 				--engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
> 				--ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> 		fi
> ```
Not DRY - same code is repeated twice, but tweaked for different builds.
It would be better to collect build specific inputs as variables first, then enter the docker run block and use these variables

e.g.
```
if build == 37:
  a=1
  b=2
  c=3
elif build == 38:
  a=4
  b=5
  c=6

docker run -a $a -b $b -c $c
```
</blockquote></details>

Done. I have attempted to remove repeat codes but with comments etc it does look a bit long

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @mattgarner)

___
*[Readme.md, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MdHc6rOC_Gkf-cmDgoL:-MdvHt56-j2nSn84U0P0:by2qskf) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/17923f4497580f00051dbb339489885692033dba/Readme.md#L55)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ## What are the limitations of this app
> ```
Which references can be used in the new version?
</blockquote></details>

Done. Suggested which references can be used

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[Readme.md, line 60 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MePngDDEwM2DH0E3-cX:-MePngDEAQ8-tp2Oemxe:b-kmjrfa) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/6793ab8569619e72270f18983e7ee730203bafde/Readme.md#L60)):*
> ```
> * hs37d5.fa (chr stripped) for build 37
> * GRCh38.no_alt_analysis_set_chr_mask21.fa (chr NOT stripped) for build 38
> ```
Does the chr prefix still matter? I thought you had modified the code to cope with either scenario
___
*[src/code.sh, line 145 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MePpSyC-SfPTFSVxloI:-MePpSyD8Ssi4GTYd7XX:b3l8ptn) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/6793ab8569619e72270f18983e7ee730203bafde/src/code.sh#L145)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
>     if $na12878; then
>         echo "NA12878 sample so running hap.py with stratification"
>         dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
>             -r ${reference_fasta_path/home\/dnanexus/data} --stratification /data/${stratification_file} \
>             --gender female --decompose --leftshift --adjust-conf-regions \
>             --engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
>             --ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
>     #Else if sample is not flagged as NA12878, run same command as above but without the stratification option
>     else
>         dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
>             -r ${reference_fasta_path/home\/dnanexus/data} \
>             --gender female --decompose --leftshift --adjust-conf-regions \
>             --engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
>             --ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> ```
</details>


# na12878=True
command="dx-docker run ..........."

if na12878:
  command += " --stratification /data/${stratification_file}"

# True: command="dx-docker run ...........  --stratification /data/${stratification_file}"
# False: command="dx-docker run ..........."

eval command

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[src/code.sh, line 145 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MePpSyC-SfPTFSVxloI:-MeQTv-E5tvZ4IH_-bE7:b6rxjzw) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/6793ab8569619e72270f18983e7ee730203bafde/src/code.sh#L145)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     if $na12878; then
>         echo "NA12878 sample so running hap.py with stratification"
>         dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
>             -r ${reference_fasta_path/home\/dnanexus/data} --stratification /data/${stratification_file} \
>             --gender female --decompose --leftshift --adjust-conf-regions \
>             --engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
>             --ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
>     #Else if sample is not flagged as NA12878, run same command as above but without the stratification option
>     else
>         dx-docker run -v /home/dnanexus/:/data pkrusche/hap.py:v0.3.9 /opt/hap.py/bin/hap.py \
>             -r ${reference_fasta_path/home\/dnanexus/data} \
>             --gender female --decompose --leftshift --adjust-conf-regions \
>             --engine vcfeval -f ${high_conf_bed_path/home\/dnanexus/data} -T ${panel_bed_path/home\/dnanexus/data} \
>             --ci-alpha 0.05 -o data/"$prefix" ${truth_vcf_path/home\/dnanexus/data} ${query_vcf_path/home\/dnanexus/data}
> ```

# na12878=True
command="dx-docker run ..........."

if na12878:
  command += " --stratification /data/${stratification_file}"

# True: command="dx-docker run ...........  --stratification /data/${stratification_file}"
# False: command="dx-docker run ..........."

eval command

</blockquote></details>

I should have put this in a code block, markdown has had fun with the formatting
```
#  na12878=True
command="dx-docker run ..........."

if na12878:
  command += " --stratification /data/${stratification_file}"

# True: command="dx-docker run ........... --stratification /data/${stratification_file}"
# False: command="dx-docker run ..........."

eval command
```
That's better

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @mattgarner)

___
*[Readme.md, line 60 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MePngDDEwM2DH0E3-cX:-MeVF7gS33Moz40hqfNh:ba90rf8) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/6793ab8569619e72270f18983e7ee730203bafde/Readme.md#L60)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> * hs37d5.fa (chr stripped) for build 37
> * GRCh38.no_alt_analysis_set_chr_mask21.fa (chr NOT stripped) for build 38
> ```
Does the chr prefix still matter? I thought you had modified the code to cope with either scenario
</blockquote></details>

I thought using a b38 fasta reference without chr might cause effects so wanted this version to be use donly. But I tested GRCh38 without Chr and runs fine so can handle both formats which is good. So have removed the (chr Not Stripped) for GRCh38. 
___
*[src/code.sh, line 145 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-MePpSyC-SfPTFSVxloI:-MeV-k6d4L_sDQFXrobF:b-7gw7dv) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/6793ab8569619e72270f18983e7ee730203bafde/src/code.sh#L145)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I should have put this in a code block, markdown has had fun with the formatting
```
#  na12878=True
command="dx-docker run ..........."

if na12878:
  command += " --stratification /data/${stratification_file}"

# True: command="dx-docker run ........... --stratification /data/${stratification_file}"
# False: command="dx-docker run ..........."

eval command
```
That's better
</blockquote></details>

Done :+1:

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[src/code.sh, line 13 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/12#-N-3hqsr2WfkbpT3edCq:-N-3hqss6MKnqDCvScTk:b-t4cny0) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/5912e1872ec9638e3d5d08db2199ac3f3b85bb20/src/code.sh#L13)):*
> ```Shell
> 
> #Install Samtools to index reference fasta files
> echo "Commands to install samtools"
> ```

building from source is slow, you would be better with a pre-compiled app asset of htslib: 

https://cuhbioinformatics.atlassian.net/wiki/spaces/DAA/pages/2465234945/DRAFT+of+htslib+bcftools+samtools+bgzip+tabix+version+1.14.0

example usage:
https://github.com/eastgenomics/eggd_generate_workbook/blob/8903637a5daf873d5f4340d3c580d179f74e1da5/dxapp.json#L189

**Pull request closed without merging**
