### PR TITLE
Di 405 reference fa tar

### PR DESCRIPTION
**Pull request by Emma-MacK**
I have updated the inputs in the .json file to remove the reference_fasta and reference_fasta_index inputs and replace them with a new input; reference_fasta_tar. I have adapted code.sh to extract the reference fasta and index files from the tar file and be found by the vcfeval tool. 

Link to Jira ticket: https://cuhbioinformatics.atlassian.net/browse/DI-405
Link to confluence page: https://cuhbioinformatics.atlassian.net/wiki/spaces/DV/pages/2992603236/eggd+vcfeval+hap.py+v1.2.1

I have also updated the app version in the .json file, the whatsNew section of the .json file, and the readme.md file to reflect the changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @chrispyatt, @Emma-MacK, and @mattgarner)

___
*[`dxapp.json` line 50 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeNKgnc1-FHhU2N0mgZ:-NeNKgnc1-FHhU2N0mg_:b-p19iez) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/dxapp.json#L50)):*
> ```JSON
>       "name": "reference_fasta_tar",
>       "label": "Reference genome fasta and index tar file",
>       "help": "Reference genome file and index contained in a tar file, either build37 or build38, strictly without chr in the chromosome number",
> ```

can we change number to field? They are not all numbers :) 
___
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeNKqdy1IA8oFYgiobO:-NeNKqdy1IA8oFYgiobP:b7now9w) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/dxapp.json#L57)):*
> ```JSON
>         {
>           "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>           "path": "/genomes/b37/hs37d5.fasta-index.tar.gz"
> ```

Can we remove a suggestion to a specific genome version please? This will be run with both, path to /genomes is fine

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @chrispyatt, @Emma-MacK, and @mattgarner)

___
*[`src/code.sh` line 34 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeNjtLO9goM9chU8NXu:-NeNjtLPBzbxPVsC0wq4:b-6klc4h) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/src/code.sh#L34)):*
> ```Shell
>         ls $reference_fasta_tar_path
>         tar -xzvf $reference_fasta_tar_path -C in/reference_fasta_tar
>         ls $reference_fasta_tar_path
> ```

What is the point of this ls? It feels the same as line 32
___
*[`src/code.sh` line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeOYa8O0zifelXMI19O:-NeOYa8O0zifelXMI19P:b-n3gyk3) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/src/code.sh#L40)):*
> ```Shell
>         # create variable that points to unpacked reference genome file in the extracted folder
>         # having /*fa leads to a path being created, adding | xargs basename strips to only the file name
>         reference_fasta=$(ls in/reference_fasta_tar/*.fa | xargs basename)
> ```

this instead of ls could be something like below as parsing file lists using ls isn't considered good practice. Please see article: http://mywiki.wooledge.org/ParsingLs



_Code snippet:_
```Shell
reference_fasta=$(find . -name '*fa' -printf '%f')
```

**Review by Emma-MacK — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Addy81, @chrispyatt, and @mattgarner)

___
*[`dxapp.json` line 50 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeNKgnc1-FHhU2N0mgZ:-NebdQsa9InFxdDMhThG:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/dxapp.json#L50)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

can we change number to field? They are not all numbers :)
</blockquote></details>

Done.
___
*[`dxapp.json` line 57 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeNKqdy1IA8oFYgiobO:-NebdOZA4YOifgKqq12z:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/dxapp.json#L57)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Can we remove a suggestion to a specific genome version please? This will be run with both, path to /genomes is fine
</blockquote></details>

Done.
___
*[`src/code.sh` line 34 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeNjtLO9goM9chU8NXu:-NebdVSq6cfoBHKmLC15:b-qinuy3) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/src/code.sh#L34)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

What is the point of this ls? It feels the same as line 32
</blockquote></details>

This was partly me testing to see how the DNAnexus built in arguments worked, I have now removed this
___
*[`src/code.sh` line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26#-NeOYa8O0zifelXMI19O:-Nebdg9w9CzzrzhfgZSu:bmtjp3a) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/30f8cad12bb229d16bc027d31c64e016dc8a3a32/src/code.sh#L40)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

this instead of ls could be something like below as parsing file lists using ls isn't considered good practice. Please see article: http://mywiki.wooledge.org/ParsingLs
</blockquote></details>

Having read the document sent I have updated the code to make use of `find`

**Review by Addy81 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrispyatt and @mattgarner)

**Pull request merged**
