### PR TITLE
Dias 152 happy v1.1.0

### PR DESCRIPTION
**Pull request by Aisha-D**
- Compatibility for b38  #11
- Remove hardcoded files and have inputs for genome build, SDF tar and stratification file #13 
- Uses docker images #7 

- Example output: https://platform.dnanexus.com/projects/G8jV97849y7yzxJf5Zxkj5bk/monitor/job/G9Y9qf849y7gkKjqP84Zv90Q

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WUC5K5jvr4waIIBRj:-N0WUC5K5jvr4waIIBRk:bq20yu0) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L2)):*
> ```JSON
> {
>   "name": "vcfeval_hap.py_v1.1.0",
> ```

can't remember if we made the decision to transition our applets to apps, @mattgarner should this be an app instead? does it matter ?
___
*[`dxapp.json` line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WUX6_4mXHXuPVe5RA:-N0WUX6_4mXHXuPVe5RB:b9qt8v4) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L72)):*
> ```JSON
>     },
>     {
>       "name": "stratification_tar",
> ```

are these in one dir? might be nice to add `suggestions` to these inputs to point where they are in DNAnexus.

Example here: https://github.com/eastgenomics/eggd_generate_bed/blob/4fdaea94f6259f049e442fa01cfcc1325275368f/dxapp.json#L31
___
*[`dxapp.json` line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WUuPP7hSly4iOVcvV:-N0WUuPP7hSly4iOVcvW:b-xziciy) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L100)):*
> ```JSON
>     "execDepends": [
>       {
>         "name": "tabix",
> ```

does this not pull remotely everytime? you already have htslib asset below so is this needed?
___
*[`dxapp.json` line 106 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WV2Xd5slCzepBhfWK:-N0WV2Xd5slCzepBhfWL:b-cj2bjv) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L106)):*
> ```JSON
>     "systemRequirements": {
>       "*": {
>         "instanceType": "mem1_ssd1_x2"
> ```

does this run any quicker with more cores to be worth a bigger instance or is it mostly single core python sadness?
___
*[`src/code.sh` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WVRDM6cdj26EMe0wf:-N0WVRDM6cdj26EMe0wg:b-300hvy) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L13)):*
> ```Shell
> 
> # samtools in htslib doesn't work as its missing a library, so
> # will it need to be downloaded
> ```

not sure this bit of the sentence makes sense



_Code quote:_
```Shell
# will it need to be downloaded
```
___
*[`src/code.sh` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WVZI0D5nUYOuFsyn_:-N0WVZI0D5nUYOuFsyna:bjng9bu) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L26)):*
> ```Shell
> else # when there IS a query vcf
>     #Download inputs from DNAnexus in parallel, these will be downloaded to /home/dnanexus/in/
>     dx download project-G8jV97849y7yzxJf5Zxkj5bk:file-G9B1yXj49y7Qk36Z79F708pK
> ```

what are these files? can we avoid using hard coded links or are we certain these won't change?
___
*[`src/code.sh` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WVpCTCrnBxhtaXuOM:-N0WVpCTCrnBxhtaXuON:b-stw0vf) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L46)):*
> ```Shell
> 	#If files are compressed, they need to be decompressed.
> 
> 	#pigz is quicker as it uses multithreads - https://stackoverflow.com/questions/14980048/how-to-decompress-with-pigz
> ```

don't think you've used pigz, so comment not needed?
___
*[`src/code.sh` line 97 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WWIE44_zYkNZCiVID:-N0WWIE5AXs-oZdhDODq:bq7bz2p) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L97)):*
> ```Shell
> 
> 	#Move all file paths to current directory
> 	mv in/*/* .
> ```

this would be better as: `find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ./`
___
*[`src/code.sh` line 98 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WWT_x3AaWNYMQ82-i:-N0WWT_x3AaWNYMQ82-j:b-58so6z) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L98)):*
> ```Shell
> 	#Move all file paths to current directory
> 	mv in/*/* .
> 	ls
> ```

needed?
___
*[`src/code.sh` line 109 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WWXHc6oOo5-VBD5dr:-N0WWXHc6oOo5-VBD5ds:boitcz2) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L109)):*
> ```Shell
> 
> 	# untar the sdf file
> 	echo $reference_sdf_tar_path
> ```

you've a lot of `echo` throughout of paths? are they needed / do you want them for future?

If you're leaving them it might be nicer to do something like `echo "ref SDF path set: ${reference_sdf_tar_path}"` so it is more informative in the logs if we need to debug anything later
___
*[`src/code.sh` line 118 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WXXUT1qwlwdjt_0E6:-N0WXXUT1qwlwdjt_0E7:b-yzbvwg) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L118)):*
> ```Shell
> 
> 	service docker start
> 	gunzip pkrusche_happy_v0.3.9.tar.gz
> ```

if the docker image is an input, can you use the variable to reference instead of hardcoding the version here?
___
*[`src/code.sh` line 141 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WXk4d9RdsLJZV4aEG:-N0WXk4d9RdsLJZV4aEH:b2vkas5) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L141)):*
> ```Shell
> 	# and the comparison method is vcfeval-hap.py
> 
> 	gunzip ga4gh_rep.py_v1.0.tar.gz
> ```

again, pls no hardcoded file names if it is an input (which it is / should be I think)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`dxapp.json` line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WUX6_4mXHXuPVe5RA:-N0_FtAN4LdLHJc8tpPL:b-f2jj01) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L72)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are these in one dir? might be nice to add `suggestions` to these inputs to point where they are in DNAnexus.

Example here: https://github.com/eastgenomics/eggd_generate_bed/blob/4fdaea94f6259f049e442fa01cfcc1325275368f/dxapp.json#L31
</blockquote></details>

No they're under two different directories, I can still point it to 001_ref which is helpful and nice
___
*[`dxapp.json` line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WUuPP7hSly4iOVcvV:-N0_GRFb-hpKe7uAiHVP:b-85eipu) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L100)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this not pull remotely everytime? you already have htslib asset below so is this needed?
</blockquote></details>

this was used before and wasn't aware htslib had to programmes to compress/uncompress. Will test it without this...
___
*[`src/code.sh` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WVRDM6cdj26EMe0wf:-N0_HzWTAyQXg2NFEGI2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L13)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not sure this bit of the sentence makes sense
</blockquote></details>

Done.
___
*[`src/code.sh` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WVpCTCrnBxhtaXuOM:-N0aWtyz8cZxNB0SEeNU:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L46)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

don't think you've used pigz, so comment not needed?
</blockquote></details>

Done.
___
*[`src/code.sh` line 97 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WWIE44_zYkNZCiVID:-N0_MI9813fDXeHoViRg:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L97)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this would be better as: `find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ./`
</blockquote></details>

Done.
___
*[`src/code.sh` line 98 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WWT_x3AaWNYMQ82-i:-N0_MIfH6homHHVwn2sF:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L98)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.
___
*[`src/code.sh` line 109 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WWXHc6oOo5-VBD5dr:-N0_MMCUB7UMuaA89Unn:b-4ezyr8) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L109)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you've a lot of `echo` throughout of paths? are they needed / do you want them for future?

If you're leaving them it might be nicer to do something like `echo "ref SDF path set: ${reference_sdf_tar_path}"` so it is more informative in the logs if we need to debug anything later
</blockquote></details>

no they were there for dev, no longer needed.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`dxapp.json` line 106 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WV2Xd5slCzepBhfWK:-N0a_-T2-H8H7dmvkcJv:b-feiw7a) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L106)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this run any quicker with more cores to be worth a bigger instance or is it mostly single core python sadness?
</blockquote></details>

tested using mem1_ssd1_x4 and it is quicker saving 6 minutes but costs are $0.0431 whereas $0.036 with the current instance. Since a cent dont see it as an issue unless it adds up over time?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`dxapp.json` line 106 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WV2Xd5slCzepBhfWK:-N0ah-Tl8773Y7Ybq2r2:b-bapoz4) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L106)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

tested using mem1_ssd1_x4 and it is quicker saving 6 minutes but costs are $0.0431 whereas $0.036 with the current instance. Since a cent dont see it as an issue unless it adds up over time?
</blockquote></details>

does this run in parallel with other jobs in the workflow? (i.e will we always be waiting on other jobs to finish when this is done), if so its not an issue it takes longer and just go with cheaper (although sometimes it can be cheaper to go quicker but this is negligible)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 106 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WV2Xd5slCzepBhfWK:-N0aiW710KOqbHXlS8Cf:b-urcbd2) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L106)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this run in parallel with other jobs in the workflow? (i.e will we always be waiting on other jobs to finish when this is done), if so its not an issue it takes longer and just go with cheaper (although sometimes it can be cheaper to go quicker but this is negligible) 
</blockquote></details>

It runs in parallel - it doesn't have any dependencies or wait on other jobs.
___
*[`src/code.sh` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WVZI0D5nUYOuFsyn_:-N0ais4s0KkxdrzFo9DN:btztn3m) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what are these files? can we avoid using hard coded links or are we certain these won't change?
</blockquote></details>

Docker images for happy - current version controlled in the app if it becomes an input then it'll need to be version controlled in the workflow. Depends on the those who maintain Dias @mattgarner   if they want to have the docker as an input or not . Are we avoiding hard coded links if we move it to an app?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D, @jethror1, and @mattgarner)

___
*[`src/code.sh` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WVZI0D5nUYOuFsyn_:-N0e_XbfDkq_V63_iaMV:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L26)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Docker images for happy - current version controlled in the app if it becomes an input then it'll need to be version controlled in the workflow. Depends on the those who maintain Dias @mattgarner   if they want to have the docker as an input or not . Are we avoiding hard coded links if we move it to an app?
</blockquote></details>

Done.
___
*[`src/code.sh` line 118 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WXXUT1qwlwdjt_0E6:-N0e_XAH6G0iNJ3sLIYM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L118)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if the docker image is an input, can you use the variable to reference instead of hardcoding the version here?
</blockquote></details>

Done.
___
*[`src/code.sh` line 141 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WXk4d9RdsLJZV4aEG:-N0e_X-S2QxNfim9YnEO:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/src/code.sh#L141)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

again, pls no hardcoded file names if it is an input (which it is / should be I think)
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N0WUC5K5jvr4waIIBRj:-N0gHHDU9RKiXh4VNAVN:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/333ddcc2a6f38c6712d31f9f28b2f1d10b2f3f6e/dxapp.json#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can't remember if we made the decision to transition our applets to apps, @mattgarner should this be an app instead? does it matter ?
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D, @jethror1, and @mattgarner)

*[a discussion](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N7VD6vK5aptIMEebwNm:-N7VD6vK5aptIMEebwNn:b-bj249m) (no related file):*
Please update the readme to reflect GRCh38 functionality (currently says it only works for 37)

___

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @Aisha-D, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 99 at r6](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N7WZyfh1wf-LGEWspSm:-N7WZyfh1wf-LGEWspSn:b9bk6ix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/c479d1098df527e18e2e89bd68e72a5cccfe91a3/dxapp.json#L99)):*
> ```JSON
>       "class": "file",
>       "patterns": ["*.tar.gz"],
>       "default": {"$dnanexus_link": {"project": "project-Fkb6Gkj433GVVvj73J7x8KbV","id": "file-GFGbK48433GzV4y54b25p43Z"}}
> ```

tiny thing but as this is json can these be formatted as :

```
default": {
    "$dnanexus_link": {
        "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
        "id": "file-GFGbK48433GzV4y54b25p43Z"
    }
}
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @jethror1)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-:-N7WcFUa9qUchcoP4Zt5:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @jethror1)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

*[a discussion](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-N7VD6vK5aptIMEebwNm:-N7WcI46D0K8uR6YBjgK:bd99zy0) (no related file):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Please update the readme to reflect GRCh38 functionality (currently says it only works for 37)
</blockquote></details>

@mattgarner waiting on you to approve and merge

___

**Review by mattgarner — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by mattgarner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/14#-:-N7ZacOfASX-iT70PcBp:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
