### PR TITLE
Remove prefix input

### PR DESCRIPTION
**Pull request by sophie22**
* remove prefix input and name output files after the full name of the input file
* update instance type
* improve docstrings throughout and reorder sections in dxapp.json

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/19)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/19)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @sophie22)

___
*[`src/code.sh` line 153 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/19#-NSFfNMABQ_EItyNEzR9:-NSFfNMABQ_EItyNEzRA:b-r9dyiu) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/8e64e6575347effdcd87a7c6fd7bf2f338b747e0/src/code.sh#L153)):*
> ```Shell
> 
> 	# Move outputs to correct directories for upload back to project
> 	cp "$prefix".summary.csv /home/dnanexus/out/summary_csv/
> ```

tiny thing but when you use `cp` it copies the whole file so you have to wait for all the read / writes (not a big deal unless files are big), using `mv` will just change the path that the file is at so is instant, more of an fyi for future than needed here



_Code quote:_
```Shell
cp
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/19)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sophie22)

**Comment by sophie22** [comment]
I'll make the change to mv rather than cp in the next branch!

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/19)* status: all files reviewed, 1 unresolved discussion (waiting on @sophie22)

**Pull request merged**
