### PR TITLE
Dias-152 happy v1.1.0 (make inputs optional)

### PR DESCRIPTION
**Pull request by Aisha-D**
- Make reference SDF inputs optional
- job without file: https://platform.dnanexus.com/projects/G8jV97849y7yzxJf5Zxkj5bk/monitor/job/GFbkKBj49y7X7jfjG9qPz6Z8 
- job with file: https://platform.dnanexus.com/projects/G8jV97849y7yzxJf5Zxkj5bk/monitor/job/GFQY86j49y7fGXbB8VkFXx3p

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15#-N8cNMnpDpp7-3UPXOyb:-N8cNMnpDpp7-3UPXOyc:b-muivzp) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/103172371eb248e40d70f6bb260cba2e6fde6a67/dxapp.json#L2)):*
> ```JSON
> {
>   "name": "vcfeval_hap.py",
> ```

should this be `eggd_` prefixed?
___
*[`dxapp.json` line 138 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15#-N8cNrW8B2XqCwhS0DAR:-N8cNrW8B2XqCwhS0DAS:b967ct2) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/103172371eb248e40d70f6bb260cba2e6fde6a67/dxapp.json#L138)):*
> ```JSON
>     }
>   ],
>   "runSpec": {
> ```

could you add a timeout in case of it hanging so it doesn't run for ever: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/2bc30538c243d906019adfa76925111194725bd9/dxapp.json#L225
___
*[`src/code.sh` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15#-N8cN1Ik6WH_hFm8WzBN:-N8cN1Ik6WH_hFm8WzBO:bsixsb) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/103172371eb248e40d70f6bb260cba2e6fde6a67/src/code.sh#L95)):*
> ```Shell
> 	if [ ! -z ${reference_sdf_tar+x}]; then
> 		mv in/reference_sdf_tar/*sdf.tar .
> 		tar -xvf *sdf.tar
> ```

this can be just one line using `-C` to specify where to put the output files:

```
tar xf in/reference_sdf_tar/*sdf.tar -C ./
```

also feel free to ignore if you dont want to change/test



_Code quote:_
```Shell
tar -xvf *sdf.tar
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15#-N8cNMnpDpp7-3UPXOyb:-N8cUD698Gl6Nvw0m15H:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/103172371eb248e40d70f6bb260cba2e6fde6a67/dxapp.json#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should this be `eggd_` prefixed?
</blockquote></details>

Done.
___
*[`dxapp.json` line 138 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15#-N8cNrW8B2XqCwhS0DAR:-N8cPAs97jwg4snL8W5t:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/103172371eb248e40d70f6bb260cba2e6fde6a67/dxapp.json#L138)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you add a timeout in case of it hanging so it doesn't run for ever: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/2bc30538c243d906019adfa76925111194725bd9/dxapp.json#L225
</blockquote></details>

Done.
___
*[`src/code.sh` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15#-N8cN1Ik6WH_hFm8WzBN:-N8cYL7L8tI_lr62_bHV:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/103172371eb248e40d70f6bb260cba2e6fde6a67/src/code.sh#L95)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this can be just one line using `-C` to specify where to put the output files:

```
tar xf in/reference_sdf_tar/*sdf.tar -C ./
```

also feel free to ignore if you dont want to change/test
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
