### PR TITLE
DI-235 make report generation optional

### PR DESCRIPTION
**Pull request by sophie22**
Since hap.py output from the summary.csv is visualised in MultiQC reports, the summary_html generated by the ga4gh rep.py Docker is not routinely required. Therefore, this functionality is made optional by adding an optional input boolean to determine whether report generation is required.
If report generation is required, then a Docker image tar must be provided to create the report.
Otherwise the app only outputs the summary.csv generated by hap.py.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/20)

### CODE REVIEW

**Comment by sophie22** [comment]
Example successful job with report generation required: https://platform.dnanexus.com/projects/GQf1Y704j4jPpxxzqYQYPB2Y/monitor/job/GQgQ8jj4j4j05G098gyX39yF
output was manually copied into https://platform.dnanexus.com/projects/GQf1Y704j4jPpxxzqYQYPB2Y/data/output/b37/take3 to keep the project tidy.
Example job without report generation: https://platform.dnanexus.com/projects/GQf1Y704j4jPpxxzqYQYPB2Y/monitor/job/GQgQxb04j4jJ78Zx6XQzpFj8

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/20)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sophie22)

___
*[`src/code.sh` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/20#-NSkxT-Y4dbYPOPND4l5:-NSkxT-Y4dbYPOPND4l6:b-ttmk9z) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/c1a291328a75fa48c1647c499e73a54b5e070e94/src/code.sh#L19)):*
> ```Shell
> if [ -z "$query_vcf" ]; then # when there's NO query file
> 	# Create an empty placeholder
> 	touch noQueryVcfFound.summary_csv
> ```

what is this for?



_Code quote:_
```Shell
touch noQueryVcfFound.summary_csv
```

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/20)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`src/code.sh` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/20#-NSkxT-Y4dbYPOPND4l5:-NSlDi-y7NSNyOKXehkJ:b-vz6m26) ([raw file](https://github.com/eastgenomics/eggd_vcfeval_hap.py/blob/c1a291328a75fa48c1647c499e73a54b5e070e94/src/code.sh#L19)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is this for?
</blockquote></details>

it is to create an empty output file in case there is no control sample on a run, but an output is expected by the app

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcfeval_hap.py/20)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @sophie22)

**Pull request merged**
